inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion:
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - "gemfiles/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/ModuleLength:
  Max: 150
